Added missing -lm to resolve undefined reference to 'sin' and 'cos' used from mpf_detector and mpf_generator
git-svn-id: http://unimrcp.googlecode.com/svn/trunk@1247 f001bc3a-424a-0410-80a0-a715b8f413a8